config/routes.rb
Rails.application.routes.draw do
  
  resources :property_certificate_sequences
  resources :request_sequence_properties
  
  resources :request_properties do
    resources :appearers
    resources :petitioners
    resources :properties

    member do
      get :print
    end

  end

  get 
  
  devise_for :users

  authenticated :user do
    root 'welcome#index'
  end

  unauthenticated :user do
    devise_scope :user do
      root 'welcome#unregistered', as: :unregistered_root
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user
  belongs_to :request_property

  validates_presence_of :user, :request_property, :register, :repertory, :date_register

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:user_id, :request_property_id, :register, :repertory, :date_register)
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.haml
= form_for @property do |f|
  - if @property.errors.any?
    #error_explanation
      %h2= "#{pluralize(@property.errors.count, "error")} prohibited this property from being saved:"
      %ul
        - @property.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :request_property
    = f.text_field :request_property
  .field
    = f.label :register
    = f.text_field :register
  .field
    = f.label :repertory
    = f.text_field :repertory
  .field
    = f.label :date_register
    = f.date_select :date_register
  .actions
    = f.submit 'Save'

app/views/properties/edit.html.haml
%h1 Editing property

= render 'form'

= link_to 'Show', @property
\|
= link_to 'Back', properties_path

app/views/properties/index.html.haml
%h1 Listing properties

%table
  %thead
    %tr
      %th User
      %th Request property
      %th Register
      %th Repertory
      %th Date register
      %th
      %th
      %th

  %tbody
    - @properties.each do |property|
      %tr
        %td= property.user
        %td= property.request_property
        %td= property.register
        %td= property.repertory
        %td= property.date_register
        %td= link_to 'Show', property
        %td= link_to 'Edit', edit_property_path(property)
        %td= link_to 'Destroy', property, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Property', new_property_path

app/views/properties/new.html.haml
%h1 New property

= render 'form'

= link_to 'Back', properties_path

app/views/properties/show.html.haml
%p#notice= notice

%p
  %b User:
  = @property.user
%p
  %b Request property:
  = @property.request_property
%p
  %b Register:
  = @property.register
%p
  %b Repertory:
  = @property.repertory
%p
  %b Date register:
  = @property.date_register

= link_to 'Edit', edit_property_path(@property)
\|
= link_to 'Back', properties_path