config/routes.rb
Rails.application.routes.draw do
  
  resources :property_certificate_sequences
  resources :request_sequence_properties
  
  resources :request_properties do
    resources :appearers
    resources :petitioners
    resources :properties

    member do
      get :print
    end

  end

  get 
  
  devise_for :users

  authenticated :user do
    root 'welcome#index'
  end

  unauthenticated :user do
    devise_scope :user do
      root 'welcome#unregistered', as: :unregistered_root
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/request_sequence_property.rb
class RequestSequenceProperty < ApplicationRecord
  belongs_to :user

  validates_presence_of :user, :sequence, :date_sequence

end

app/controllers/request_sequence_properties_controller.rb
class RequestSequencePropertiesController < ApplicationController
  before_action :set_request_sequence_property, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /request_sequence_properties
  # GET /request_sequence_properties.json
  def index
    @request_sequence_properties = RequestSequenceProperty.all
  end

  # GET /request_sequence_properties/1
  # GET /request_sequence_properties/1.json
  def show
  end

  # GET /request_sequence_properties/new
  def new
    @request_sequence_property = RequestSequenceProperty.new
  end

  # GET /request_sequence_properties/1/edit
  def edit
  end

  # POST /request_sequence_properties
  # POST /request_sequence_properties.json
  def create
    @request_sequence_property = current_user.request_sequence_property.new(request_sequence_property_params)

    respond_to do |format|
      if @request_sequence_property.save
        format.html { redirect_to @request_sequence_property, notice: 'Request sequence property was successfully created.' }
        format.json { render :show, status: :created, location: @request_sequence_property }
      else
        format.html { render :new }
        format.json { render json: @request_sequence_property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /request_sequence_properties/1
  # PATCH/PUT /request_sequence_properties/1.json
  def update
    respond_to do |format|
      if @request_sequence_property.update(request_sequence_property_params)
        format.html { redirect_to @request_sequence_property, notice: 'Request sequence property was successfully updated.' }
        format.json { render :show, status: :ok, location: @request_sequence_property }
      else
        format.html { render :edit }
        format.json { render json: @request_sequence_property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /request_sequence_properties/1
  # DELETE /request_sequence_properties/1.json
  def destroy
    @request_sequence_property.destroy
    respond_to do |format|
      format.html { redirect_to request_sequence_properties_url, notice: 'Request sequence property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request_sequence_property
      @request_sequence_property = RequestSequenceProperty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_sequence_property_params
      params.require(:request_sequence_property).permit(:user_id, :sequence, :date_sequence)
    end
end

app/helpers/request_sequence_properties_helper.rb
module RequestSequencePropertiesHelper
end

app/views/request_sequence_properties/_form.html.haml
= form_for @request_sequence_property do |f|
  - if @request_sequence_property.errors.any?
    #error_explanation
      %h2= "#{pluralize(@request_sequence_property.errors.count, "error")} prohibited this request_sequence_property from being saved:"
      %ul
        - @request_sequence_property.errors.full_messages.each do |msg|
          %li= msg


  .field
    = f.label :sequence
    = f.number_field :sequence
  .field
    = f.label :date_sequence
    = f.number_field :date_sequence
  .actions
    = f.submit 'Save'

app/views/request_sequence_properties/edit.html.haml
%h1 Editing request_sequence_property

= render 'form'

= link_to 'Show', @request_sequence_property
\|
= link_to 'Back', request_sequence_properties_path

app/views/request_sequence_properties/index.html.haml
%h1 Listing request_sequence_properties

%table
  %thead
    %tr
      %th User
      %th Sequence
      %th Date sequence
      %th
      %th
      %th

  %tbody
    - @request_sequence_properties.each do |request_sequence_property|
      %tr
        %td= request_sequence_property.user
        %td= request_sequence_property.sequence
        %td= request_sequence_property.date_sequence
        %td= link_to 'Show', request_sequence_property
        %td= link_to 'Edit', edit_request_sequence_property_path(request_sequence_property)
        %td= link_to 'Destroy', request_sequence_property, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Request sequence property', new_request_sequence_property_path

app/views/request_sequence_properties/new.html.haml
%h1 New request_sequence_property

= render 'form'

= link_to 'Back', request_sequence_properties_path

app/views/request_sequence_properties/show.html.haml
%p#notice= notice

%p
  %b User:
  = @request_sequence_property.user
%p
  %b Sequence:
  = @request_sequence_property.sequence
%p
  %b Date sequence:
  = @request_sequence_property.date_sequence

= link_to 'Edit', edit_request_sequence_property_path(@request_sequence_property)
\|
= link_to 'Back', request_sequence_properties_path