config/routes.rb
Rails.application.routes.draw do
  
  resources :property_certificate_sequences
  resources :request_sequence_properties
  
  resources :request_properties do
    resources :appearers
    resources :petitioners
    resources :properties

    member do
      get :print
    end

  end

  get 
  
  devise_for :users

  authenticated :user do
    root 'welcome#index'
  end

  unauthenticated :user do
    devise_scope :user do
      root 'welcome#unregistered', as: :unregistered_root
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/petitioner.rb
class Petitioner < ApplicationRecord
  belongs_to :user
  belongs_to :request_property

  validates_presence_of :user, :request_property, :last_name, :name, :document, :civil_status, :address, :phone, :email, :infodigital

end

app/controllers/petitioners_controller.rb
class PetitionersController < ApplicationController
  before_action :set_petitioner, only: [:show, :edit, :update, :destroy]

  # GET /petitioners
  # GET /petitioners.json
  def index
    @petitioners = Petitioner.all
  end

  # GET /petitioners/1
  # GET /petitioners/1.json
  def show
  end

  # GET /petitioners/new
  def new
    @petitioner = Petitioner.new
  end

  # GET /petitioners/1/edit
  def edit
  end

  # POST /petitioners
  # POST /petitioners.json
  def create
    @petitioner = Petitioner.new(petitioner_params)

    respond_to do |format|
      if @petitioner.save
        format.html { redirect_to @petitioner, notice: 'Petitioner was successfully created.' }
        format.json { render :show, status: :created, location: @petitioner }
      else
        format.html { render :new }
        format.json { render json: @petitioner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /petitioners/1
  # PATCH/PUT /petitioners/1.json
  def update
    respond_to do |format|
      if @petitioner.update(petitioner_params)
        format.html { redirect_to @petitioner, notice: 'Petitioner was successfully updated.' }
        format.json { render :show, status: :ok, location: @petitioner }
      else
        format.html { render :edit }
        format.json { render json: @petitioner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /petitioners/1
  # DELETE /petitioners/1.json
  def destroy
    @petitioner.destroy
    respond_to do |format|
      format.html { redirect_to petitioners_url, notice: 'Petitioner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_petitioner
      @petitioner = Petitioner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def petitioner_params
      params.require(:petitioner).permit(:user_id, :request_property_id, :last_name, :name, :document, :civil_status, :address, :phone, :email, :infodigital)
    end
end

app/helpers/petitioners_helper.rb
module PetitionersHelper
end

app/views/petitioners/_form.html.haml
= form_for @petitioner do |f|
  - if @petitioner.errors.any?
    #error_explanation
      %h2= "#{pluralize(@petitioner.errors.count, "error")} prohibited this petitioner from being saved:"
      %ul
        - @petitioner.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :request_property
    = f.text_field :request_property
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :document
    = f.text_field :document
  .field
    = f.label :civil_status
    = f.text_field :civil_status
  .field
    = f.label :address
    = f.text_field :address
  .field
    = f.label :phone
    = f.number_field :phone
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :infodigital
    = f.text_field :infodigital
  .actions
    = f.submit 'Save'

app/views/petitioners/edit.html.haml
%h1 Editing petitioner

= render 'form'

= link_to 'Show', @petitioner
\|
= link_to 'Back', petitioners_path

app/views/petitioners/index.html.haml
%h1 Listing petitioners

%table
  %thead
    %tr
      %th User
      %th Request property
      %th Last name
      %th Name
      %th Document
      %th Civil status
      %th Address
      %th Phone
      %th Email
      %th Infodigital
      %th
      %th
      %th

  %tbody
    - @petitioners.each do |petitioner|
      %tr
        %td= petitioner.user
        %td= petitioner.request_property
        %td= petitioner.last_name
        %td= petitioner.name
        %td= petitioner.document
        %td= petitioner.civil_status
        %td= petitioner.address
        %td= petitioner.phone
        %td= petitioner.email
        %td= petitioner.infodigital
        %td= link_to 'Show', petitioner
        %td= link_to 'Edit', edit_petitioner_path(petitioner)
        %td= link_to 'Destroy', petitioner, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Petitioner', new_petitioner_path

app/views/petitioners/new.html.haml
%h1 New petitioner

= render 'form'

= link_to 'Back', petitioners_path

app/views/petitioners/show.html.haml
%p#notice= notice

%p
  %b User:
  = @petitioner.user
%p
  %b Request property:
  = @petitioner.request_property
%p
  %b Last name:
  = @petitioner.last_name
%p
  %b Name:
  = @petitioner.name
%p
  %b Document:
  = @petitioner.document
%p
  %b Civil status:
  = @petitioner.civil_status
%p
  %b Address:
  = @petitioner.address
%p
  %b Phone:
  = @petitioner.phone
%p
  %b Email:
  = @petitioner.email
%p
  %b Infodigital:
  = @petitioner.infodigital

= link_to 'Edit', edit_petitioner_path(@petitioner)
\|
= link_to 'Back', petitioners_path