config/routes.rb
Rails.application.routes.draw do
  
  resources :property_certificate_sequences
  resources :request_sequence_properties
  
  resources :request_properties do
    resources :appearers
    resources :petitioners
    resources :properties

    member do
      get :print
    end

  end

  get 
  
  devise_for :users

  authenticated :user do
    root 'welcome#index'
  end

  unauthenticated :user do
    devise_scope :user do
      root 'welcome#unregistered', as: :unregistered_root
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/property_certificate_sequence.rb
class PropertyCertificateSequence < ApplicationRecord
  belongs_to :user

  validates_presence_of :user, :sequence, :date_sequence

end

app/controllers/property_certificate_sequences_controller.rb
class PropertyCertificateSequencesController < ApplicationController
  before_action :set_property_certificate_sequence, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /property_certificate_sequences
  # GET /property_certificate_sequences.json
  def index
    @property_certificate_sequences = PropertyCertificateSequence.all
  end

  # GET /property_certificate_sequences/1
  # GET /property_certificate_sequences/1.json
  def show
  end

  # GET /property_certificate_sequences/new
  def new
    @property_certificate_sequence = PropertyCertificateSequence.new
  end

  # GET /property_certificate_sequences/1/edit
  def edit
  end

  # POST /property_certificate_sequences
  # POST /property_certificate_sequences.json
  def create
    @property_certificate_sequence = current_user.property_certificate_sequence.new(property_certificate_sequence_params)

    respond_to do |format|
      if @property_certificate_sequence.save
        format.html { redirect_to @property_certificate_sequence, notice: 'Property certificate sequence was successfully created.' }
        format.json { render :show, status: :created, location: @property_certificate_sequence }
      else
        format.html { render :new }
        format.json { render json: @property_certificate_sequence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /property_certificate_sequences/1
  # PATCH/PUT /property_certificate_sequences/1.json
  def update
    respond_to do |format|
      if @property_certificate_sequence.update(property_certificate_sequence_params)
        format.html { redirect_to @property_certificate_sequence, notice: 'Property certificate sequence was successfully updated.' }
        format.json { render :show, status: :ok, location: @property_certificate_sequence }
      else
        format.html { render :edit }
        format.json { render json: @property_certificate_sequence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /property_certificate_sequences/1
  # DELETE /property_certificate_sequences/1.json
  def destroy
    @property_certificate_sequence.destroy
    respond_to do |format|
      format.html { redirect_to property_certificate_sequences_url, notice: 'Property certificate sequence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property_certificate_sequence
      @property_certificate_sequence = PropertyCertificateSequence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_certificate_sequence_params
      params.require(:property_certificate_sequence).permit(:user_id, :sequence, :date_sequence)
    end
end

app/helpers/property_certificate_sequences_helper.rb
module PropertyCertificateSequencesHelper
end

app/views/property_certificate_sequences/_form.html.haml
= form_for @property_certificate_sequence do |f|
  - if @property_certificate_sequence.errors.any?
    #error_explanation
      %h2= "#{pluralize(@property_certificate_sequence.errors.count, "error")} prohibited this property_certificate_sequence from being saved:"
      %ul
        - @property_certificate_sequence.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :sequence
    = f.number_field :sequence
  .field
    = f.label :date_sequence
    = f.number_field :date_sequence
  .actions
    = f.submit 'Save'

app/views/property_certificate_sequences/edit.html.haml
%h1 Editing property_certificate_sequence

= render 'form'

= link_to 'Show', @property_certificate_sequence
\|
= link_to 'Back', property_certificate_sequences_path

app/views/property_certificate_sequences/index.html.haml
%h1 Listing property_certificate_sequences

%table
  %thead
    %tr
      %th User
      %th Sequence
      %th Date sequence
      %th
      %th
      %th

  %tbody
    - @property_certificate_sequences.each do |property_certificate_sequence|
      %tr
        %td= property_certificate_sequence.user
        %td= property_certificate_sequence.sequence
        %td= property_certificate_sequence.date_sequence
        %td= link_to 'Show', property_certificate_sequence
        %td= link_to 'Edit', edit_property_certificate_sequence_path(property_certificate_sequence)
        %td= link_to 'Destroy', property_certificate_sequence, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Property certificate sequence', new_property_certificate_sequence_path

app/views/property_certificate_sequences/new.html.haml
%h1 New property_certificate_sequence

= render 'form'

= link_to 'Back', property_certificate_sequences_path

app/views/property_certificate_sequences/show.html.haml
%p#notice= notice

%p
  %b User:
  = @property_certificate_sequence.user
%p
  %b Sequence:
  = @property_certificate_sequence.sequence
%p
  %b Date sequence:
  = @property_certificate_sequence.date_sequence

= link_to 'Edit', edit_property_certificate_sequence_path(@property_certificate_sequence)
\|
= link_to 'Back', property_certificate_sequences_path